### ISSUE TITLE
EC2 instances usage should only count 'running' instances

### ISSUE THREAD

**Issue by pdecat** [jantman/awslimitchecker#101]
Hi,

I believe the _Running On-Demand EC2 instances_ AWS service limits only count EC2 instances in the _running_ state.

I could not find any explicit statements on that subject in the AWS documentation but I have got the case where my instances count is above the service limit:

    # awslimitchecker --list-limits | grep "Running On-Demand EC2 instances"
    EC2/Running On-Demand EC2 instances                    200 (API)

    # awslimitchecker --show-usage | grep "Running On-Demand EC2 instances"
    EC2/Running On-Demand EC2 instances                    207

Filtering on the instance state, I currently have:

* 170 _running_ instances
* 22 _stopped_ instances
* 11 _terminated_ instances

**Comment by jantman** [comment]
@pdecat You're right, sorry. I've missed that this whole time (I guess because none of my employers leave many stopped instances around). The relevant code is https://github.com/jantman/awslimitchecker/blob/master/awslimitchecker/services/ec2.py#L83

I'll try to get a fix for this tonight or tomorrow. Thanks for taking the time to make me aware of this!

**Comment by jantman** [comment]
@pdecat I'm not sure how I missed this, but the code that I referenced above handles reserved instances; it explicitly queries all active reservations (by AZ and instance type) and subtracts that from the on-demand instances. It does not, however, ignore instances in the "stopped" or "terminated" [instance state](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_InstanceState.html).

I've got a fix for this and will be making a bugfix release shortly.
