### ISSUE TITLE
Add support for EBS st1 and sc1 volume types.

### ISSUE THREAD

**Issue by gimballock** [jantman/awslimitchecker#189]
## Feature Request

Currently I see the following error when running limit checker:
"ERROR:awslimitchecker.services.ebs:ERROR - unknown volume type 'st1' for volume vol-xxxxxxxx; not counting"

These volume types are fairly recent and the source looks pretty simple to extend. I will attempt to provide a PR for this fix..

**Comment by jantman** [comment]
@gimballock thanks for the heads up. No worry about a PR unless you want to, I should be able to get this done this afternoon or this evening.

**Comment by gimballock** [comment]
FYI These aren't yet supported in TA yet so I picked some limit labels in
the meantime:
'Throughput Optimized (HDD) volume storage (GiB)'
'Cold (HDD) volume storage (GiB)'

**Comment by jantman** [comment]
@gimballock these limits *are* listed in the "Limits" page on the EC2 console (not that that's an indication of what TA will call them:

"Max Cold HDD (SC1) Storage in TiB" and "Max Throughput Optimized HDD (ST1) Storage in TiB" (though the API reports in GB, and that's what all of the limit checker stuff uses.

Did you want to try your hand at a PR, or should I work on the changes? It turns out my schedule is a bit more busy than I'd thought, and tomorrow evening is probably more likely for a fix and release.

**Comment by gimballock** [comment]
Yea I'll send you a PR, I have it ready except for these label name changes.

**Comment by gimballock** [comment]
Actually are you sure you want to use 'Max' and (<vol_type>) in the label?
The labels I have now are more inline with existing labels:
'Provisioned IOPS (SSD) storage (GiB)'
'General Purpose (SSD) volume storage (GiB)'
'Magnetic volume storage (GiB)'
'Throughput Optimized (HDD) volume storage (GiB)'
'Cold (HDD) volume storage (GiB)'

**Comment by jantman** [comment]
Ok, yours look fine to me. There's already a built-in way of mapping limits that have different names in Trusted Advisor (since TA always runs late...)

Thanks!

**Comment by jantman** [comment]
This was fixed in #190 and released just now as 0.4.4. Thanks!!!!
