### ISSUE TITLE
EC2  - Actual AWS limits != AWSLimitChecker limits list

### ISSUE THREAD

**Issue by lastboy** [jantman/awslimitchecker#210]
Hi,

Today, I got a Critical "Running On-Demand t2.medium instances" limit notification
I checked my account via the AWS console: "EC2 Services Limits"
My account's defaults is not like the defaults I get from AWSLimitChecker and that's why I got the Critical notification

Why is that? Am I'm missing something?
BTW We have changed our account defaults

-Arik

**Comment by jantman** [comment]
@lastboy 

There is no way to retrieve [those limits](http://awslimitchecker.readthedocs.io/en/latest/limits.html#ec2) via the API; AWS provides information on some limits via the API and others via Trusted Advisor (see http://awslimitchecker.readthedocs.io/en/latest/limits.html for details), but the instance-type-specific Running Instances limits aren't among them.

Until AWS fixes this, you must specifically pass in the new limit values to AWSLimitChecker, either via the ``-L/--limit`` command line flag or (if using via Python) via [set_limit_override()](http://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.checker.html#awslimitchecker.checker.AwsLimitChecker.set_limit_override) or [set_limit_overrides()](http://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.checker.html#awslimitchecker.checker.AwsLimitChecker.set_limit_overrides).

e.g. at my current employer, we rely on [Trusted Advisor](http://awslimitchecker.readthedocs.io/en/latest/limits.html#trusted-advisor-data) and [API](http://awslimitchecker.readthedocs.io/en/latest/limits.html#limits-retrieved-from-service-apis) to populate the limit values they can, but maintain JSON files for each region for each of our accounts that we manually update with the limits that Trusted Advisor and the APIs don't provide information on.

I know this is pretty ugly, but there's no way to retrieve the limits programmatically via the APIs, and screen-scraping the Console is both slow and explicitly forbidden in the terms of service.

**Comment by lastboy** [comment]
@jantman  

I assume that, just wanted to double check with you. Thank you for the details.

Related to that question: Not many, but there were cases where we could not get the instances we demanded since Amazon didn't have enough resources to allocate. It means that  even tough you have set a limit, you will not get alerted since this is an amazon issue. It would be awesome to get that kind of information...

-Arik

**Comment by jantman** [comment]
Arik,

We've had issues with Amazon instance capacity as well. As far as I know, there is no public insight into this; AWS' [Troubleshooting Instance Capacity page, for the InsufficientInstanceCapacity error](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-capacity.html#instance-capacity-insufficient) basically says to wait a while, request fewer instances, try a different AZ, or try a different instance size. RightScale has some [docs on it too](http://docs.rightscale.com/faq/clouds/aws/How_come_I_get_an_insufficient_capacity_error_when_launching_an_EC2_instance.html), which basically say the same thing. There's definitely no API to find this out (especially since Amazon tends to consider their actual capacity and how they manage it to be a secret), and I haven't found this exposed in any sort of status page or API.

From what I can tell, this isn't really considered an error condition by AWS, at least not enough to merit reporting it publicly on a status page. We know that AWS (from the little they talk about what they do behind the scenes) is really big on utilizing their infrastructure resources as much as possible. I can only assume that they have very little (comparatively speaking, very little in terms of their scale) in the way of idle compute resources, and power on or provision new hardware essentially as-needed. Hence every once in a while, demand will increase quickly and there's a bit of a delay before resources are available. Anecdotally, most of the times I've seen this happen in us-east-1 have been around 8-11 AM Eastern, when traffic jumps.

The "real" answer at least according to Amazon's best practices and what some of their massive-scale customers say, is that apps should be architected to be at least multi-AZ, if not multi-region, and that you shouldn't rely on a particular AZ having capacity any more than you should rely on a particular AZ being working correctly.

I agree that these aren't "good" answers, and I wish they provided more insight into the inner workings and how much capacity is available where, but I can agree with the experts that from a reliability perspective, none of us should be relying on a single AZ working correctly or having capacity.

**Comment by lastboy** [comment]
@jantman 

If we are in the ugly business, well, I really don't like to copy and paste stuff :)
In this case I used phantomjs to come-up with a tool for getting the json api via the AWS console.

**Comment by jantman** [comment]
Ok, cool. Yeah, I agree that this is pretty ugly either way... I've put pressure on our account rep at my day job, but I'm not sure how much they can really do. Maybe I'll try another ping...

**Comment by lastboy** [comment]
@jantman 

I got the JSON files with the limits and I'm trying to map the names.
In the AWS Console > EC2 > Limits  There's a section about **Hosts limits**:
- Running On-Demand c3 hosts
- Running On-Demand c4 hosts
- Running On-Demand d2 hosts
- Running On-Demand g2 hosts
- Running On-Demand i2 hosts
- Running On-Demand m3 hosts
- Running On-Demand m4 hosts
- Running On-Demand r3 hosts
- Running On-Demand x1 hosts

Is it supported? If so I couldn't match the data with the actual limits docs.

-Arik

**Comment by jantman** [comment]
@lastboy those limits are, as far as I know, for [EC2 Dedicated Hosts](https://aws.amazon.com/ec2/dedicated-hosts/)... but I've never touched those.

No, the EC2 Host limits aren't currently supported. I also don't have a way of testing a feature request for them, as neither I nor anyone I know uses EC2 Dedicated Hosts.
