### ISSUE TITLE
add support for ignoring limit checks based on resource name / dynamodb table name.

### ISSUE THREAD

**Issue by lllmaa** [jantman/awslimitchecker#307]
### Feature Description

It would be nice to have ability to skip certain checks based on the limit and resource name (or table name, in case of dynamo), to have the ability to suppress warnings on subsequent checks.

### Use Cases

Currently we get the following warning:
DynamoDB/Global Secondary Indexes  (limit 5) WARNING: my-table-name=4

We know that this table is at 4, and will remain that way. If someone modifies the table, by adding 2 more secondary indexes, we are fine that the update fails. We want to "whitelist/suppress" this alert for this table permanently. 
But we still would like to maintain ability to have this alert for other/new tables, when they appear on the same aws account/region, and start to reach the limit of secondary indexes.

### Testing Assistance

i'm able to test this feature.

**Comment by jantman** [comment]
@lllmaa I certainly understand the use case for this. It sounds like it would be a valuable addition for some users, but I'm not sure that I can commit to when I can implement this. I'd certainly be open to pull requests.

**Comment by jantman** [comment]
@lllmaa As this issue has been open for over a year with no further comment, I'm going to close it. If you came up with a solution for this, a comment would be appreciated.

If this is still an issue for you or any other users, please feel free to comment.

As it stands right now, the way I achieve this in my current employer's implementation is to use the Python API for awslimitchecker from a wrapper script (ours is very similar to [docs/examples/check_aws_limits.py](https://github.com/jantman/awslimitchecker/blob/c5e9ec339e67b1bb97f9f792c9f92c34db5e8994/docs/examples/check_aws_limits.py)) and do some additional analysis on each AwsLimit's [get_warnings()](https://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.limit.html#awslimitchecker.limit.AwsLimit.get_warnings) and [get_criticals()](https://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.limit.html#awslimitchecker.limit.AwsLimit.get_criticals), ignoring what we want to.

**Comment by ddelnano** [comment]
@lllmaa this is now possible with the `--skip-check` flag (available as of 6.1.6). See the docs [here](https://awslimitchecker.readthedocs.io/en/6.1.6/cli_usage.html#disabling-specific-checks).

**Comment by bergkampsliew** [comment]
@ddelnano , thanks for updating on this old ticket 🥇 
can i confirm with you that command below can be used to skip check for specific resource id/name? so, it's not just skipping the check type.

for example,
awslimitchecker --skip-check='EC2/Max launch specifications per spot fleet  (limit 50) WARNING: sfr-98e516f0-62f8-47ad-ada6-444da23fe6c5=42'

**Comment by jantman** [comment]
@bergkampsliew I'm pretty sure that this issue is asking for something different from ``--skip-check``. In the example you gave, the argument would be ``--skip-check='EC2/Max launch specifications per spot fleet'`` and it would skip the "Max launch specifications per spot fleet" check for the EC2 service completely.

The current ways to handle a case like the above are either to set a [limit override](https://awslimitchecker.readthedocs.io/en/latest/cli_usage.html#overriding-limits) or [threshold override](https://awslimitchecker.readthedocs.io/en/latest/cli_usage.html#set-custom-thresholds) for that service, or if you really really want to just ignore one single resource, to run awslimitchecker from a Python wrapper script (see [examples in the docs](https://awslimitchecker.readthedocs.io/en/latest/python_usage.html)) and ignore the single resource at that level (see the API docs detailing the return value for [AwsLimitChecker.check_thresholds()](https://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.checker.html#awslimitchecker.checker.AwsLimitChecker.check_thresholds) and the [AwsLimit class's](https://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.limit.html#awslimitchecker.limit.AwsLimit) [get_warnings(https://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.limit.html#awslimitchecker.limit.AwsLimit.get_warnings)]() and [get_criticals(https://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.limit.html#awslimitchecker.limit.AwsLimit.get_criticals)]() methods, which return instances of the [AwsLimitUsage](https://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.limit.html#awslimitchecker.limit.AwsLimitUsage) class, which can be interrogated for usage information at the resource level.

**Comment by bergkampsliew** [comment]
thanks for the reply and suggestion @jantman  
yeah, i was trying to get quick confirmation as i didn't read through the code commit/changes
anyway skip-check is good addition
