### ISSUE TITLE
RDS 'DB snapshots per user' is using old limit value, should be 100 instead of 50

### ISSUE THREAD

**Issue by bergkampsliew** [jantman/awslimitchecker#314]
## Bug Report

Incorrect limit check for RDS 'DB snapshots per user'. Should be 100 instead of 50 under the default value - https://github.com/jantman/awslimitchecker/blob/master/awslimitchecker/services/rds.py#L171

### Version

awslimitchecker 2.0.0

### Supporting Software Versions

Python 2.7.9, not using virtualenv

### Actual Output

Flag that the limit has been reached.

### Expected Output

Flag that the limit has been reached.

### Testing Assistance

No

**Comment by jantman** [comment]
@bergkampsliew Thanks for reporting this. Yes, the 'DB snapshots per user' (now listed on the [RDS limits page](http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_rds) as "Manual snapshots") is now 100. This appears to have changed on January 30, 2017 according to the archive.org snapshot of the service limits page.

I'm not yet sure when the next release will be out, but this will be fixed in it.

I'm a bit confused by your actual vs expected output though. If awslimitchecker thinks the limit is 50 when it's really 100, shouldn't it be giving a false positive instead of a false negative?

**Comment by bergkampsliew** [comment]
@jantman , thanks for the reply.
I made a mistake when comparing result and looking at wrong region - I'll correct my description above, sorry about it.

There is actually an alert (as below) appeared during the execution.
RDS/DB snapshots per user  (limit 100) CRITICAL: 100
My guess this comes from the Trusted Advisor or direct API?
If that is correct, then this is not a bug but rather improvement item (to the default value at https://github.com/jantman/awslimitchecker/blob/master/awslimitchecker/services/rds.py#L171 , I believe)

**Comment by jantman** [comment]
Ahhh yeah, I forgot about that. RDS (unlike almost all other services, because this is decided by each individual service team) exposes _all_ of its service limits via its API. So even though the default in awslimitchecker is wrong, the default should never be used for RDS.

So yeah this isn't a bug that anyone should ever hit unless the RDS API stops providing limit info (which I think would be very unlikely), but I'm going to leave it labeled Bug just so I make sure to fix it in the next release.

Thanks again for such a detailed report!
