### ISSUE TITLE
[Feature Request] Support multiple AWS accounts

### ISSUE THREAD

**Issue by Mortinke** [jantman/awslimitchecker#323]
## Feature Request

Support multiple AWS accounts

### Feature Description

At the moment, awslimitchecker support only one AWS account with the `-A` argument. It would be nice if several accounts are supported.

### Use Cases

Currently, we have 39 AWS accounts which are all managed by a maintenance account. I'd be grateful if we could check all AWS accounts with one execution instead of calling the awslimitchecker 39 times.

**Comment by jantman** [comment]
@Mortinke My answer to this is similar to my answer to #324 : if you need this, you should use the [Python API](http://awslimitchecker.readthedocs.io/en/latest/python_usage.html) via a wrapper script, such as the [check_aws_limits.py example](https://github.com/jantman/awslimitchecker/blob/master/docs/examples/check_aws_limits.py) (which also has example [unit tests](https://github.com/jantman/awslimitchecker/blob/master/docs/examples/test_check_aws_limits.py) and a [brief overview here](https://github.com/jantman/awslimitchecker/tree/master/docs/examples#check_aws_limitspy)).

IMO, multiple accounts is a bit of a complicated situation and tends to be organization-specific. As an example:

* Do you run with assumed roles, or different static creds, or do you get temporary creds from some service like Vault?
* Who gets notifications for different accounts? The same team, or different teams? How do you determine the contact method/details (i.e. email address, pagerduty service, etc.) for different accounts?
* How do you tell which accounts are production (i.e. send to a pager) and which are dev/test/lab (and only notify via email)?
* How do you know which regions are active and need to be checked in which accounts?

Because of the wide variety of answers to questions like these and more for different users, there isn't official multi-account support built in to awslimitchecker itself.

If you're interested, I can add a multi-account example based on the code that my current employer uses. We run awslimitchecker from Jenkins, one job per account, with per-account limit and threshold overrides, and assumed roles for all but the account that Jenkins runs in. However an example could just as easily run for all accounts and combine the results.

**Comment by Mortinke** [comment]
Hi @jantman,

thanks for your quick reply. I would be very happy if you can add a multi account example! 
I had seen the API wrapper script, but I would prefer a build in functionality.  

I'd also like to use a Jenkins job to check our 39 AWS accounts. The number of our AWS accounts will continue to increase in the future and the usage of 39 different wrapper scripts can already be confusing.
I'm worried that the solution with separate jenkins jobs and separate API wrapper scripts will no longer scale at 50 to 100 AWS accounts. 

Regarding your questions:
* We would use assumed role in all accounts, which have trusted relationship to our jenkins instance role.
* I haven't considered notifications, as this isn't supported by default - or did I miss anything? For this I would use a map/dictionary with account id and e-mail.
* We use only one region (eu-central-1). Currently, only one region is supported by awslimitchecker and supporting multiple regions wouldn't be necessary for multiple accounts. I see this as a separate feature.

**Comment by jantman** [comment]
I understand those concerns. We only use one wrapper script, the Jenkins jobs just call it with account-specific arguments (and are themselves generated by a JobDSL groovy script). But that's really just an artifact of our environment and structure, and that different accounts are supported by different teams and have different levels of urgency.

No, you didn't miss anything, notifications aren't built-in. We handle that at the Jenkins level.

I can work up a wrapper example for you in the next day or two. A few other questions:

* How would you configure the assumed roles? Also in JSON? I know you'd [commented before](https://github.com/jantman/awslimitchecker/issues/325#issue-278897065) with an example of a single JSON file. Would it work for you if the wrapper script handled a directory of per-account JSON files, which each specified the role to assume as well as the regions for the account (defaulting to only eu-central-1) and the limit and threshold overrides?
* How would you want the output? All criticals and then all warnings, or broken up by account?

**Comment by Mortinke** [comment]
Use only one wrapper script with account specific arguments sounds much better :)

We use one static role per service (securitymonkey, aardvard, awslimitchecker, ...) in each account, so it's not necessary to specify different roles per account. However, it's totally fine, if we have the possibility to specify the role and the region with a directory in the json file.

In my opinion, the output should grouped/sorted by account, something like this:
```
<account_id>
    <service>/<limit>               (limit <current_limit> {WARNING|CRTICAL}: <usage>
    <service>/<limit>               (limit <current_limit> {WARNING|CRTICAL}: <usage>
    ....
<account_id>
    <service>/<limit>               (limit <current_limit> {WARNING|CRTICAL}: <usage>
    <service>/<limit>               (limit <current_limit> {WARNING|CRTICAL}: <usage>
.....
```

Thank you in   advance for your help in this matter!

**Comment by jantman** [comment]
@Mortinke I have an example script and configuration at:

https://github.com/jantman/awslimitchecker/tree/issues/323/docs/examples/multi-region_multi-account

The output format is slightly different, but I think it meets most of the requirements. Please take a look when you have a chance and tell me if this looks useful to you.

**Comment by Mortinke** [comment]
Thank you very very much, it works very well!

**Comment by jantman** [comment]
Cool, thanks! I'm glad that suited your needs!

If there's any way I can improve it further, please feel free to ask. I'm going to reopen this for now, just as a reminder to myself to merge those examples to the master branch in the next release.
