### ISSUE TITLE
Overrride limit when we can call limit API

### ISSUE THREAD

**Issue by di1214** [jantman/awslimitchecker#327]
I am working on a forked repo for this project and one thing bothers me is that I am not sure which behaviour is expected when using --limit. It is very useful that we could override default limits with our increased limits, however, it also overrides those limits we could get from _update_limits_from_api().

@jantman Maybe i am totally wrong on this, but if i am not, can we put a check saying override won't override limits that can be get from api calls. The reason is that we have situations where AWS support ticket says limit on X is increased to Y but AWS did not actually increase it.

**Comment by jantman** [comment]
@di1214 ok. Are you planning on submitting any of your work in the fork as a pull request?

The behavior that you describe is _expected_. Whether it makes complete sense or not, I guess I'm not sure. I imagine that most users do what I do... we only specify limit overrides for limits that aren't [retrieved via API or Trusted Advisor](http://awslimitchecker.readthedocs.io/en/latest/limits.html).

Changing that would require some changes to [AwsLimit.get_limit()](http://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.limit.html#awslimitchecker.limit.AwsLimit.get_limit) and probably [AwsLimit.get_limit_source()](http://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.limit.html#awslimitchecker.limit.AwsLimit.get_limit_source) but is certainly do-able. I guess my only worry is about changing a relatively internal and opaque behavior like that, and whether any other users are relying on the current behavior.

Does that answer your question? Since you didn't fill out the issue template, I'm assuming that this was a question about if/how you could do that in your fork, and not a request for this feature (or to consider the current behavior a bug)?

**Comment by di1214** [comment]
@jantman That makes sense. I may want to add a check in my fork to ignore override for limits that could get from API. Our use case is a bit different. We have to track our limit based on AWS support ticket which we could not entirely trust. I was planning to use whatever we tracked to override the default, but i guess i will have to implement the ignore in my code now. The problem for me is that we have a big team and i do not even know which resources are used and which of them could `_update_limits_from_api`. I won't know that before others complain the result of this tool :(

Regarding the PR, i think i may be able to submit ECS and Directory Service I added. I have also added Appstream/workspaces but it may only apply to our current use case (AWS doesn't have much api support for this two, not like other resources.) BTW, I really liked the way you setup the project. Have all tests generated automatically, so i just need to focus on put some code there. However, I a bit busy(lazy) now, not all tests are implemented for services I added. I don't want to send a PR and break your code coverage. But i will create a PR as soon as I have time

**Comment by jantman** [comment]
@di1214 Ok, I suppose I understand that. I'm working on a considerably smaller team, and our documentation just tells everyone to look at http://awslimitchecker.readthedocs.io/en/latest/limits.html before adding an override. As to the trust issue, we've had occasional problems with AWS Support saying they raised a limit and not actually raising it, or raising the wrong limit or the wrong region. I'm not sure there's really any way around that, for limits that aren't reported via API or Trusted Advisor.

For what it's worth, you may want to look into https://github.com/Yipit/awslimits - I've never used it, but it's a web interface written around awslimitchecker, and I believe it also automatically sets the overrides from support tickets (though that still doesn't account for mistakes by AWS Support).

If you have working implementations for ECS and Directory Service, I'd certainly be interested in a PR to get them merged. While it's preferable to have full test coverage, it's not required... if you don't have a chance to do it, I can add the test coverage before the next release.

**Comment by jantman** [comment]
@di1214 I'm going to be working on your PR #328 this weekend; sorry it's taken me so long to get around to it.

Are you still interested in a solution to this limit override problem, or have you come up with something that works?

**Comment by jantman** [comment]
Pinging back again. @di1214 are you still looking for a solution to this, or should I close this issue?

**Comment by di1214** [comment]
@jantman sorry, i thought i replied. i will close it
