### ISSUE TITLE
Limits for ALBs and Classic LBs are now provided separately

### ISSUE THREAD

**Issue by SpokMike** [jantman/awslimitchecker#412]
## Bug Report

We have the limit checker running hourly against an AWS account, wrapped in some code that alerts us when a limit threshold is passed. We recently received an "Active Load Balancers" alert in an AWS account in which we run only ALBs (no classics or NLBs). Despite increasing our ALB limit with AWS, the limit checker continued to report the same warning, as well as the same limit (20), until we also raised the limit on classic load balancers as well.

Looking at the code for the ELB class, I can see where it's collecting usage and limits for each service (ALB vs classic), but I can't see where it's returning those separate limits (the names in the limits dicts don't seem to match up with what is being returned by the AWS API in call cases). The notes on that same code page indicate this is intentional, but I believe AWS is now watching these limits separately.

Entirely possible I'm missing something, but I thought it was worth raising.

**Comment by jantman** [comment]
@SpokMike apologies for setting this sit so long without a response. I'm on vacation for the rest of the week, but I'll do my best to dig into this early next week.

**Comment by jantman** [comment]
This is really interesting... I guess it must be a recent change.

The main service limits page at https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_elastic_load_balancer no longer has mention of ALBs and Classic sharing the "Load balancers per region" limit.

Prior to https://github.com/awsdocs existing, I used to save that service limits page to a GitHub repo every day (or was it week?) since there was no documentation history, and no public information at all on when limits changed. I stopped doing that in August 2018 when https://github.com/awsdocs was announced.

As of that time, the [Load balancers per region limits](https://github.com/jantman/aws-docs-history/blob/master/docs.aws.amazon.com/general/aws_service_limits.html.md#elastic-load-balancing-limits-limits_elastic_load_balancer) were shared between ALBs and Classic.

Furthermore, while the published [ALB limits page](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-limits.html) no longer says that the limit is shared, the GitHub repo - theoretically the source of these docs, I thought - [still does](https://github.com/awsdocs/elb-application-load-balancers-user-guide/blob/master/doc_source/load-balancer-limits.md) list that the limit is shared. I hate to ding in an issue on an unrelated project, but maybe @julieso has an idea about whether the awsdocs repos are still accurate, or whether they actually lag behind the official/published docs?

Either way, yes, this does seem to be a bug and it looks as though "Active load balancers per region" is now a separate limit for ALBs and Classic, though **once again** this seems to have been a completely unannounced change that's not present in the [ALB User Guide Documentation History](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/doc-history.html).

I'll try within the next few days to add a separate ``Active ALBs per region`` limit for ALBs.

**Comment by julieso** [comment]
Yes, this was a recent change. I updated the repo for the User Guide for Classic Load Balancers shortly thereafter, but I somehow missed updating the repo for the User Guide for Application Load Balancers. You'll find the latest documentation updates there now.

**Comment by jantman** [comment]
@julieso Ah, ok, thank you **so** much!

**Comment by SpokMike** [comment]
Thanks for the detailed response and background, @jantman. I appreciate your work on this project in general, and your efforts to implement a fix on this issue in particular.

**Comment by jantman** [comment]
The fix for this has been released in [7.0.0](https://github.com/jantman/awslimitchecker/releases/tag/7.0.0) and is now live on PyPI.
