### ISSUE TITLE
Unable to get the current usage details of services

### ISSUE THREAD

**Issue by Pearl1594** [jantman/awslimitchecker#428]
I've been trying to use the awslimitchecker package to fetch the service resource usage details, however, it yields in an empty list. Is there something wrong in the way I'm using the package?
Following is what I've attempted:

## Fails to give the usage details
from awslimitchecker.checker import AwsLimitChecker
aws_limit = AwsLimitChecker(profile_name="xxxx", region="us-east-1")

for s, svc in aws_limit.services.items():
    if s == 'S3':
        for k,v in svc.limits.items():
            print v.get_current_usage()   // Empty list: []
			
			
However, the same one done directly, yeilds the correct value:
import boto3
def connect():
    session = boto3.Session(profile_name="majid")
    conn = session.resource("s3", region_name="us-east-1")
    count =0
    for bkt in conn.buckets.all():
            count += 1
    print count

connect() // prints the correct count

**Comment by jantman** [comment]
@Pearl1594 That's happening because you're never actually getting the usage. If you want to check current usage, then before looking at the limits, you will need to call ``aws_limit.find_usage()``.

Furthermore, you should not be iterating ``aws_limit.services`` directly.

The [prometheus example in the docs](https://github.com/jantman/awslimitchecker/blob/master/docs/examples/prometheus.py) is somewhat similar to your use case.

Your example should work if rewritten as:

```python
from awslimitchecker.checker import AwsLimitChecker
aws_limit = AwsLimitChecker(profile_name="xxxx", region="us-east-1")
aws_limit.find_usage()
for service_name, svc_limits in sorted(checker.get_limits().items()):
    if service_name != 'S3':
        continue
    for limit_name, limit in sorted(svc_limits.items()):
        print(limit.get_current_usage())
```

Furthermore, that above code will calculate usage for __all__ services, which can take quite some time. If you really only want the S3 service, you can pass that to the [find_usage() method](https://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.checker.html#awslimitchecker.checker.AwsLimitChecker.find_usage) by replacing the third line of the above with:

```python
aws_limit.find_usage(['S3'])
```
