### ISSUE TITLE
Add support to check available IP addresses in a subnet

### ISSUE THREAD

**Issue by ryangardner** [jantman/awslimitchecker#469]
In our AWS deployment, we have some interesting restrictions around the creation of new subnets in our accounts. For this reason, we like to monitor the number of IP addresses we have available in the different subnets and alert if we are starting to get close to running out of them. 

I took a quick look - the available IP addresses and the CIDR block get returned already by the describe subnet call - getting the number of IP addresses in the subnet from the CIDR could be calculated manually or could be done by a library like https://python-iptools.readthedocs.io/en/v0.6.1/ - but I wasn't entirely sure how to best integrate it with the existing vpc service.

**Comment by ryangardner** [comment]
If you have any general guidance on how you think it should be implemented, I can try to implement this and submit a PR with it to you

**Comment by jantman** [comment]
@ryangardner Apologies for the delayed response on this, I've been quite busy lately and haven't had much time to attend to my personal open source projects.

This is an interesting feature request. I'm familiar with the subnet creation restrictions (turns out we work for the same company)... but my team has a separate tool for monitoring subnet usage, which is separate from awslimitchecker and not open source.

Regarding implementation, the Python built-in [ipaddress module](https://docs.python.org/3/library/ipaddress.html), available since 3.3, provides the [ipnetwork](https://docs.python.org/3/library/ipaddress.html#ipaddress.ip_network) constructor. IpNetwork objects can be iterated over to get their possible IPs (``num_ips = len([x for x in ipaddress.ip_network('10.102.0.0/24')])``) so all that's left is subtracting the Amazon-reserved addresses.

Reaching back in my memory to when my team wrote our internal script for this, I think I remember why a subnet usage check never made it into awslimitchecker: there are a lot of AWS services that consume IP addresses and can automatically scale in and out - i.e. Auto-Scaling Groups (ASGs), ECS Capacity Providers, autoscaling ECS Tasks with VPC networking, a whole bunch of resource types supported by Application Auto Scaling, Lambda, Aurora Auto Scaling, etc. While it would be relatively straightforward to provide an alert on just the _currently_ used IP addresses in a subnet (granted this can change quite a bit if you're doing lots of red/black / blue/green deployments), there's a really massive amount of service-specific logic needed in order to calculate the "worst-case" IP usage if every service running in the subnet scales all the way out.

Finally, up until now at least, my standpoint has been that "used IP addresses in a subnet" might be an inherit limit enforced by... mathematics... but it's not an actual AWS Service Limit (as defined in AWS' documentation of service limits), so awslimitchecker doesn't do anything with it. Moreover, given the scale-out issue, I'm inclined to not implement this lest awslimitchecker advertises itself as being able to alert on low addresses, and then someone's app massively scales out and runs out of IPs, and we can't detect this situation.

I _think_ that one of the AWS services - either Trusted Advisor or Personal Health Dashboard - provides an alert for subnets that are running low on free addresses. Alternatively, if you're only concerned about _current_ address usage and not the scale-out condition, it should be relatively easy to develop a Lambda or some other standalone script that calculates this information and triggers an alert. I have a sample that I can show you (privately) that alerts via PagerDuty, and also includes logic to contact the owners of resources that are tagged with an ``ownerEmail`` tag.

**Comment by jantman** [comment]
Stale issue; closing.
