### ISSUE TITLE
Add support for AWS EKS service, now it's available via Service Quota

### ISSUE THREAD

**Issue by quocdung3007** [jantman/awslimitchecker#472]
### Feature Description

I want to monitor all the limits for EKS via Service Quota which is recently supported by AWS https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-quotas-can-now-be-managed-through-aws-service-quotas/

### Use Cases

This is will be useful for those using AWS EKS service to monitor their usage and raise the limit before it hits the limit.

### Testing Assistance

I can help to test it when it's available.

**Comment by jantman** [comment]
Please accept my apologies for not responding sooner; I've been quite busy lately and unable to dedicate any time to my open source projects.

Now that these limits are available via Service Quota, this should be much easier to implement.

I can't make any promises on when, or even if, I'll get this implemented myself. But if anyone is willing to implement this, pull requests are greatly appreciated, and there's [documentation on how to add support for a new Service](https://awslimitchecker.readthedocs.io/en/latest/development.html#adding-new-services).

**Comment by sebasrp** [comment]
I'm working on this pull request

**Comment by jantman** [comment]
A fix for this issue has been merged to the [develop](https://github.com/jantman/awslimitchecker/tree/develop) branch and is slated for release in 10.0.0 on Monday, December 7, 2020. Anyone who is able to test the fix is strongly encouraged to do so, and comment on this issue with their results. Instructions for installing awslimitchecker from a git branch are available in the [Installing for Development documentation](https://awslimitchecker.readthedocs.io/en/latest/development.html#installing-for-development).

**Comment by jantman** [comment]
This has been fixed in [10.0.0](https://github.com/jantman/awslimitchecker/releases/tag/10.0.0), which is now [live on PyPI](https://pypi.org/project/awslimitchecker/) and is being built on the [Docker hub](https://hub.docker.com/r/jantman/awslimitchecker) right now. Thank you so much for the contribution!
