### ISSUE TITLE
VPC-related limit changes

### ISSUE THREAD

**Issue by varuzam** [jantman/awslimitchecker#498]
## Bug Report
The checker reports
`EC2/Rules per VPC security group (limit 60) CRITICAL: sg-0ea8209947164dc4b=64.`

But in AWS service quota UI the limit is 100. Does the checker check the actual limit or compare against the default limit?

### Version
9.0.0

### Installation Method
docker image

**Comment by jwu2** [comment]
It appears that the quota should be `Inbound or outbound rules per security group` in `VPC` group with quota code: `L-0EA8095F`. Not sure if this was a change at AWS side. Current code may have a hard-coded limit of 60.

**Comment by jantman** [comment]
Apologies for the delay on getting to this.

So it looks like there's a few things going on here, related to the VPC Security Group limits:

1. According to the [VPC quotas documentation](https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html#vpc-limits-security-groups), the ``Rules per VPC security group`` limit still has a default of 60. If the Quotas UI is telling you 100, then your limit has been increased beyond the default. Per the [awslimitchecker 9.0.0 documentation](https://awslimitchecker.readthedocs.io/en/latest/limits.html#ec2), as of 9.0.0, awslimitchecker had no way of automatically retrieving this limit, so it would fall back to the hard-coded published default unless you overrode that via the command line or a configuration file.
2. Yes, Service Quotas now exposes a "Inbound or outbound rules per security group" quota, "L-0EA8095F", which starts at a value of 60.0 on new accounts.
3. Also according to the [VPC quotas documentation](https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html#vpc-limits-security-groups), it does in fact look like there is no longer a "Security groups per VPC" limit, but there is now a new "VPC security groups per Region" limit.

I'll most likely spend some time comparing the current VPC-related limits that awslimitchecker knows about with what both the documentation and Service Quotas report, and then open a new PR to supersede #504, to update all of that.

**Comment by jantman** [comment]
A fix for this issue has been merged to the [develop](https://github.com/jantman/awslimitchecker/tree/develop) branch and is slated for release in 10.0.0 on Monday, December 7, 2020. Anyone who is able to test the fix is strongly encouraged to do so, and comment on this issue with their results. Instructions for installing awslimitchecker from a git branch are available in the [Installing for Development documentation](https://awslimitchecker.readthedocs.io/en/latest/development.html#installing-for-development).

**Comment by jwu2** [comment]
I have tested a few changes:

- `Rules per VPC security group` (VPC > Inbound or outbound rules per security group) is working properly, plus it also returns current limit value if that has been raised, so override is unnecessary

- 'VPC security groups per Region' returns correct data.

Both quotas are listed under VPC service instead of EC2 on AWS console. It might be a good idea to match this.

Again, thanks @jantman very much for fixing the issues.

**Comment by jantman** [comment]
Thank you so much!

Regarding "VPC" as opposed to "EC2", I'm very hesitant to move/rename limits, as it breaks many existing users.

**Comment by jantman** [comment]
This has been fixed in [10.0.0](https://github.com/jantman/awslimitchecker/releases/tag/10.0.0), which is now [live on PyPI](https://pypi.org/project/awslimitchecker/) and is being built on the [Docker hub](https://hub.docker.com/r/jantman/awslimitchecker) right now. Thank you so much for the contribution!
