### ISSUE TITLE
Incorrect 'Network interfaces per Region' limit

### ISSUE THREAD

**Issue by jwu2** [jantman/awslimitchecker#501]
### Version

9.0.0

### Installation Method

Docker

### Supporting Software Versions

3.8.6

### Actual Output

Currently the limit checker queries DescribeAccountAttributes API for "max-instances" attribute, then calculate with logic below:
This limit is the greater of either the default limit (350) or your On-Demand Instance limit multiplied by 5. The default limit for On-Demand Instances is 20.

### Expected Output

According to https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeAccountAttributes.html, "max-instances" attribute is no longer supported.

Instead this limit is available in Service Quotas with Quota code `L-DF5E4CA3` and the default value is 5000.

### Testing Assistance

Yes

**Comment by jantman** [comment]
Thanks for reporting this. Yes, that's all correct. I'll work up a fix for this shortly.

**Comment by jantman** [comment]
A fix for this issue has been merged to the [develop](https://github.com/jantman/awslimitchecker/tree/develop) branch and is slated for release in 10.0.0 on Monday, December 7, 2020. Anyone who is able to test the fix is strongly encouraged to do so, and comment on this issue with their results. Instructions for installing awslimitchecker from a git branch are available in the [Installing for Development documentation](https://awslimitchecker.readthedocs.io/en/latest/development.html#installing-for-development).

**Comment by jwu2** [comment]
I have tested this check in the develop branch and can confirm it's working properly.

@jantman, thank you for very much for the fix.

**Comment by jantman** [comment]
Thanks so much for the confirmation!

**Comment by jantman** [comment]
This has been fixed in [10.0.0](https://github.com/jantman/awslimitchecker/releases/tag/10.0.0), which is now [live on PyPI](https://pypi.org/project/awslimitchecker/) and is being built on the [Docker hub](https://hub.docker.com/r/jantman/awslimitchecker) right now. Thank you so much for the contribution!
